# Numpy

Numpy is the fundamental package for scientific computing in python. it is a python library that provides a multidimensional array object,
various derived objects(Such as masked arrays and matrices), and as assortment of routines for fast operations on arrays, including mathematical, 
logical, shape manipulation , sorting, I/O, discrete fourier transforms, basic linear algrbra, basic statistical operations, random 
simulation and much more.

At the core of the numpy package, is ndarry object. This encapsulates n-dimensional arrays of homogeneous data types, wioth many operations
being performed in compiled code for performance. There are homogeneous data types,with many operations being performed in compiled code for 
performance. There are several differences between numpy arrays and the standard python sequences:
    
Numpy arrays have a fixed sixe at creation , unlike python lists(Which can grow dynamically). Changingnthe size of an ndarray will create a
new array and delete the original. The elements in a numpy array are all required  to be of the same data type.and thus will be the same size in memory. 

The exception: One can have arrays of (Python, including numpy) objects, there by allowing for arrays of different size elements.
    
Numpy arrays facilite advanced mathematical can other types of operations on large numbers of data. Typically, such operations are executed 
more efficiently and with less code than is possible using python's built-in sequences.

A growing plethora of scientific and mathematical python - based packages are using numpy arrays through these typically support python - sequence input,
they convert such input to numpy arrays prior to processing, and they often output numpy arrays. in other words, in order to efficiently use much (perhaps even most)
of today's scientific/mathematical python- based software, just knowing how to use python's built-in sequence types insufficent - one also needs
to know how to use numpy arays.

The points about sequence size and speed are particularly important in scientific computing. as a simple example, consider the case of multiplying each element in a 1-D sequence with the 
corresponding elements in another sequence of the same length. If the data are stored in two python lists, a and b, we could iterate 
over each elements.

**This produces the correct answer, but if a and b each contin millions of numbers, we will pay the price for the ineffeciencies of looping in python. we 
could accomplish the same task much more quickly in c by writting (for clarity we neglect variable declaration and initializations, memory allocation, etc.)**

numpy is general-purpose array-processing package. it provides a high-performance multi dimensional array object and tools for working 
with these arrays. it is the fundamental package for scientific computing with python. it is open-source software. it contains various features including these important onces:

# Uses for numpy

1. A powerful N-dimensional array object.

2. Sophisticated (broadcasting) funtions.

3. Tools for integrating C/C++ and fortran code.

4. Useful linear algebra, fourier transform, and random number capabilities.



esides its obvious scientific uses, Numpy in python can also be used as an efficient multi-dimentional container of generic data. Aritrary data types can be defined using numpy which allows numpy to seamlessly and speedily integrate with a wide variety of databases.

1.  It is a table of elements (usually numbers), all the same type, indexed by  a tuple of positive integers.

2.  In numpy, dimensions are called axes. the number of axes is rank.

3.  Numpy's array class is called ndarray. it is also known by the alias array.



**Examples:**

In this examples, we are creating a two- dimensional array which has it has 2 axis. The first axis(dimension) is of leangth 2.
i.e., the number of row, and the second axis(dimension) is of length 3, i.e., the number of columns. The overall shape of the array can be represented as (2,3). 

**Arrays in Numpy**

In [22]:
import numpy as np

#creating array object
arr = np.array([[1,2,3], [4,2,5]])

#print type of arr object
print("Array is of type:", type(arr))

#print array dimensions (axes)
print("No. of dimension:", arr.ndim)

#print shape of array
print("Shape of array:", arr.shape)

#print size (Total number of elements) of array
print("Size of array:", arr.size)

#printing type of elements in array
print("Array stores elements of type:", arr.dtype)

Array is of type: <class 'numpy.ndarray'>
No. of dimension: 2
Shape of array: (2, 3)
Size of array: 6
Array stores elements of type: int32


In [4]:
aniket = np.array([[11,22,33,44], [8,64,9,81]])

#print type of arr object
print("Array is of type:", type(aniket))

#print array dimensions (axes)
print("No. of dimension:", aniket.ndim)

#print shape of array
print("Shape of array:", aniket.shape)

#print size (Total number of elements) of array
print("Size of array:", aniket.size)

#printing type of elements in array
print("Array stores elements of type:", aniket.dtype)

Array is of type: <class 'numpy.ndarray'>
No. of dimension: 2
Shape of array: (2, 4)
Size of array: 8
Array stores elements of type: int32


In [54]:
gadekar = np.array([[[121,195,817,151,471],[159,874,963,524,846]],[[487,856,987,415,265],[456,854,957,115,765]]])

#print type of arr object
print("Array is of type:", type(gadekar))

#print array dimensions (axes)
print("No. of dimension:", gadekar.ndim)

#print shape of array
print("Shape of array:", gadekar.shape)

#print size (Total number of elements) of array
print("Size of array:", gadekar.size)

#printing type of elements in array
print("Array stores elements of type:", gadekar.dtype)

gadekar

Array is of type: <class 'numpy.ndarray'>
No. of dimension: 3
Shape of array: (2, 2, 5)
Size of array: 20
Array stores elements of type: int32


array([[[121, 195, 817, 151, 471],
        [159, 874, 963, 524, 846]],

       [[487, 856, 987, 415, 265],
        [456, 854, 957, 115, 765]]])

In [25]:
import numpy as np

#creating array from list with type float
a = np.array([[1,2,4], [5,8,7]],dtype = 'float')
print("Array created using passed list:\n",a)

#creating array from tuple
b = np.array((1,3,2))
print("\nArray created using passed typle:\n", b)

#creating a 3x4 array with all zeros
c = np.zeros((3,4))
print("\nAn array initialized with all zeros:\n", c)

#creating a constant value array of complex type #3 rows and 3 colums (3,3)
d = np.full((3,3),6, dtype = 'complex')
print("\nAn array initialized with all 6s."
      "Array type is complex:\n", d)

#craete an array with random values 
e = np.random.random((2,2))
print("\nA Random array\n:", e)

#create a sequence of integers
#from 0 to 30 with steps of 5
f = np.arange(0,30,5)
print("\nA Sequential array with steps of 5\n:", f)

#create a sequence of 10 values in range of 0 to 5.
g = np.linspace(0,5,10)
print("\nA Sequential array with 10 values between"
      "0 to 5\n:", g)

# Reshaping 3x4 array to 2x2x3 array #2 row 2 row 3 colums
arr= np.array([[1,2,3,4],
              [5,2,4,2],
              [1,2,0,1]])

newarr= arr.reshape(2,2,3)

print("\nOriginal array:\n", arr)
print("Reshaped array:\n", newarr)

#Flatten array
arr = np.array([[1,2,3],[4,5,6]])
flarr = arr.flatten()

print("\nOriginal array:\n", arr)
print("Fattened array:\n", flarr)



Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]

Array created using passed typle:
 [1 3 2]

An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]

A Random array
: [[0.91730229 0.89180734]
 [0.66869466 0.94562681]]

A Sequential array with steps of 5
: [ 0  5 10 15 20 25]

A Sequential array with 10 values between0 to 5
: [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]

Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]


# Numpy Array Indexing

Knowing the basics of numpy array in indexing is important for analyzing and manipulating the array objects. Numpy in python offers many ways to do array indexing.

Slicing - Just like lists in python. numpy array can be sliced. as arrays can be multidimensional. you need to specify a slice for each dimension of the array.

Integer array indexing - In this method, lists are passed for indexing for each dimension. One-to-one mapping of corresponding. elements is done to consutruct a new 
arbitary array.

Boolean array indexing - This method is used when we want to pick elements from the array which satisfy some condition.

In [30]:
#indexing in numpy
import numpy as np

# An example array
arr = np.array([[5,8.6,9,-9],
               [5,6,9.8,-9],
               [2.6,-9,86,5],
               [-9,63,8.9,7]])

#slicing array
temp = arr[:3,::2]
print("Array with first 3 rows and alternate"
     "coloumns(0,3):\n", temp)

temp = arr[:2,::3]
print("Array with first 3 rows and alternate"
     "coloumns(0,3):\n", temp)

#Integer array indexing example

temp = arr[[0,1,2,3],[3,2,1,0]]
print("\nElements at indices (0,3), (1,2),(2,1),"
     "(3,0):\n", temp)

#boolean array indexing examples
cond = arr > 0 #cond is a boolean array
temp = arr[cond]
print("\nElements greater than 0:\n", temp)

Array with first 3 rows and alternatecoloumns(0,3):
 [[ 5.   9. ]
 [ 5.   9.8]
 [ 2.6 86. ]]
Array with first 3 rows and alternatecoloumns(0,3):
 [[ 5. -9.]
 [ 5. -9.]]

Elements at indices (0,3), (1,2),(2,1),(3,0):
 [-9.   9.8 -9.  -9. ]

Elements greater than 0:
 [ 5.   8.6  9.   5.   6.   9.8  2.6 86.   5.  63.   8.9  7. ]


In [49]:
import numpy as np

#creating array object
table = np.array([[2,4,6,8,10], [3,6,9,12,15],[4,8,12,16,20],[5,10,15,20,25]])

#print type of arr object
print("Array is of type:", type(table))

#print array dimensions (axes)
print("No. of dimension:", table.ndim)

#print shape of array
print("Shape of array:", table.shape)

#print size (Total number of elements) of array
print("Size of array:", table.size)

#printing type of elements in array
print("Array stores elements of type:", table.dtype)

#creating array from list with type float

a = np.array([[2,4,6,8,10], [3,6,9,12,15],[4,8,12,16,20],[5,10,15,20,25]],dtype = 'float')
print("Array created using passed list:\n",a)

#creating array from tuple
table_six = np.array((6,12,18,24,30))
print("\nArray created using passed typle:\n", table_six)

#creating a 3x4 array with all zeros
zero = np.zeros((5,5))
print("\nAn array initialized with all zeros:\n", zero)

#creating a constant value array of complex type #3 rows and 3 colums (3,3)
complex_number = np.full((3,6),2, dtype = 'complex')
print("\nAn array initialized with all 6s."
      "Array type is complex:\n", complex_number)

#craete an array with random values 
random_numbers = np.random.random((2,5))
print("\nA Random array\n:", random_numbers)

#create a sequence of integers
#from 0 to 30 with steps of 5
f = np.arange(0,100,10)
print("\nA Sequential array with steps of 5\n:", f)

#create a sequence of 10 values in range of 0 to 5.
g = np.linspace(1,10,2)
print("\nA Sequential array with 10 values between"
      "0 to 5\n:", g)

# Reshaping 3x4 array to 2x2x3 array #2 row 2 row 3 colums

new_table= table.reshape(2,2,5)

print("\nOriginal array:\n", table)
print("Reshaped array:\n", new_table)

#Flatten array

new_flarr = table.flatten()

print("\nOriginal array:\n", table)
print("Fattened array:\n", new_flarr)

# An example array
table = np.array([[2,4,6,8,10], [3,6,9,12,15],[4,8,12,16,20],[5,10,15,20,25]])
#slicing array
temp = table[:3,::2]
print("Array with first 3 rows and alternate"
     "coloumns(0,3):\n", temp)

temp = table[:3,::4]
print("Array with first 3 rows and alternate"
     "coloumns(0,3):\n", temp)

#Integer array indexing example
temp = table[[0,1,2,3],[3,2,1,0]]
print("\nElements at indices (0,3), (1,2),(2,1),"
     "(3,0):\n", temp)

#boolean array indexing examples
cond = table > 2 #cond is a boolean array
temp = table[cond]
print("\nElements greater than 0:\n", temp)

Array is of type: <class 'numpy.ndarray'>
No. of dimension: 2
Shape of array: (4, 5)
Size of array: 20
Array stores elements of type: int32
Array created using passed list:
 [[ 2.  4.  6.  8. 10.]
 [ 3.  6.  9. 12. 15.]
 [ 4.  8. 12. 16. 20.]
 [ 5. 10. 15. 20. 25.]]

Array created using passed typle:
 [ 6 12 18 24 30]

An array initialized with all zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

An array initialized with all 6s.Array type is complex:
 [[2.+0.j 2.+0.j 2.+0.j 2.+0.j 2.+0.j 2.+0.j]
 [2.+0.j 2.+0.j 2.+0.j 2.+0.j 2.+0.j 2.+0.j]
 [2.+0.j 2.+0.j 2.+0.j 2.+0.j 2.+0.j 2.+0.j]]

A Random array
: [[0.93179702 0.64481653 0.74736219 0.11362612 0.0052922 ]
 [0.71927517 0.75304128 0.57354604 0.32199281 0.08136904]]

A Sequential array with steps of 5
: [ 0 10 20 30 40 50 60 70 80 90]

A Sequential array with 10 values between0 to 5
: [ 1. 10.]

Original array:
 [[ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]

# What are python modules and packages?

Modular programming refers to the process of breaking a large, un wieldy programming task into separate, smaller, more manageable subtasks or modules.
Individual modules can then be cobbled together like building blocks to create a large applications.

There are several advantages to modularizing code in a large applications.

**Simplicity :**  Rather than focusing on the entire problems at hand, a module typically focusses on one relatively small portion of the problem.
if you are working on a single module. you'll have a smaller problem domain to wrap your head around. This makes developement easier and less error-prone.

**Maintainability :**  Modules are typically designed so that enforce logical boundries between different problem domains. If module 
written in a way that minimizes interdependency, there is decreased likelihood that modifications to a single module will have an impact
on other part of the program.(You may even be able to make changes to a module without having any knowledge of the application outside that module.)
This makes it more viable for a team of many programmers to work collaboratively on a large appplication.

**Reusability :** Functionlity defined in a single module can be easily reused (Through an appropriately defined interface) by other parts
of the application. This eleminates the need to duplicate code.

Functions, modules and packages are all constructs in python that promote code modularization.

Python modules : overview

# What are the arrays?

Containers which are able to store more than one item at the same time.

# What is python module?

A python module is a file containing python definitions and statements. A module can define functions, classes and variables. A
module can also include runnable code. Grouping related code into a module makes easier to understand and use.it also makes the code 
logically organized.

Modules are the pre-defined that contain the python codes which depict the basic functionalities of class, methods, variables, etc.
it consists of different functions, classes in a group of files inside a directory. Modules can also be termed as libraries. These are basically
the pre-defined methods that can be used to make the code more efficient and reduce redundancy (error). modules bind the code and reduce
the repetitions of functions frequently used in the code. Thus, it makes the code much clear and easy to understand.

A module's contents are accessed with the import statement. A library is a collection of modules, but the terms are often used interchangeably.
especially since many libraries only consist of a single module, so don't worry if you mix them.

Examples of some popular python modules are:
    

**OS**

**Math**

**Time**

**Matplotlib**

On such library in python is numpy 

Numpy is a python package. it stands for 'Numerical python'. it is a library consisting of multidimentional array objects and collection of 
routines for processing of array. The numpy package is the workhorse of data analysis, machine learining, and scientific computing in the python 
eco-system. it vastly simplifies manipulating and crunhing vectors and matrices. Some of python's leading package rely on numpy as a 
fundamental piece of their infrastructure(examples include scikit- learn, scipy, pandas and tensorflow). Beyond the ability to slice 
and dice numeric data, mastering numpy will give you an edge when dealing and debugging with advanced usecases in these libraries.


In that situations would we need to crunch vectors and matrices?

Numpy offers ingenious techniques for effectively loading, storing and manipulating in-memory data in python. The topic is very broad:
datasets can come from a wide range of sources and a wide range of formate, including be collections of documents, collections of images, collections
of sound clips, collections of numerical measurements, or nearly anything else. despite this heterogeneity, it will help us to think  of all 
data fundamentally as arrays of numbers(vectors and matrices).

Images - particularly digital images-can be thought of as simple two dimentional array of numbers

representing pixel brightness 

across the area.

sound clips can be thought of as one-dimensional arrays of intensity versus time.

text can be converted in various ways into numerical representations, perhaps binary digits represnting the frequency of certain
words or pairs of words.

No matters what the data are, The first step in making it analyzable will be to transform them into arrays of numbers(vectors and matrices).

# Lets import the Numpy library in our environment

In [36]:
#Statement to import the numpy Library.
import numpy as np

     keywords : import
                                                                                          as np
          |  
                                                                                
        import                                 numpy                                        |
   
                                                                                          Alias
                                                 |
         
     
                                        module to be imported              
     

The most important object defined in numpy is an N- dimentional array.

In [39]:
#Statement to import the numpy library
import numpy as np

In [40]:
#one- dimensional array of some prime numbers
prime_array = np.array([2,3,5,7,11])
print(prime_array)
type(prime_array)

[ 2  3  5  7 11]


numpy.ndarray

            command                                                                Numpy array
                                                                                       1
          np.array([1,2,3])-------------------------------------------------------     2
                                                                                       3

In [41]:
type(prime_array)

numpy.ndarray

In [42]:
#crate a two- dementional array
another_array = np.array([[1,2],[3,4]])
print(another_array)

[[1 2]
 [3 4]]


           
    
               np.array([[1,2],[3,4]])------------------------------------------------------- 1  2
                                                                                              3  4

In [45]:
#crate a three- dementional array
threeD_array = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[6,7],[9,0]]])
print(threeD_array)
print(threeD_array.shape)

three_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(three_array)
type(three_array)



[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[6 7]
  [9 0]]]
(3, 2, 2)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

In [62]:
import numpy as np

#creating array object
mix = np.array([[[10,20,-30,40,50], [6,-8,74,96,12.3]],[[15,8,9.6,-9,12],[5,1.0,-15,20,25]]])

#print type of arr object
print("Array is of type:", type(mix))

#print array dimensions (axes)
print("No. of dimension:", mix.ndim)

#print shape of array
print("Shape of array:", mix.shape)

#print size (Total number of elements) of array
print("Size of array:", mix.size)

#printing type of elements in array
print("Array stores elements of type:", mix.dtype)

#creating array from list with type float

a = np.array([[[10,20,-30,40,50], [6,-8,74,96,12.3]],[[15,8,9.6,-9,12],[5,1.0,-15,20,25]]],dtype = 'float')
print("Array created using passed list:\n",a)

#creating array from tuple
table_ten = np.array((10,20,30,40,50,60,70,80,90,100))
print("\nArray created using passed typle:\n", table_ten)

#creating a 3x4 array with all zeros
zeros = np.zeros((2,10))
print("\nAn array initialized with all zeros:\n", zeros)

#creating a constant value array of complex type #3 rows and 3 colums (3,3)
complex_number = np.full((3,7),8, dtype = 'complex')
print("\nAn array initialized with all 8s."
      "Array type is complex:\n", complex_number)

#craete an array with random values 
random_numbers = np.random.random((3,3))
print("\nA Random array\n:", random_numbers)

#create a sequence of integers
#from 0 to 30 with steps of 5
f = np.arange(1,50,5)
print("\nA Sequential array with steps of 5\n:", f)

#create a sequence of 10 values in range of 0 to 5.
g = np.linspace(1,50,5)
print("\nA Sequential array with 10 values between"
      "0 to 5\n:", g)

# Reshaping 3x4 array to 2x2x3 array #2 row 2 row 3 colums

new_table= mix.reshape(2,2,5)

print("\nOriginal array:\n", mix)
print("Reshaped array:\n", new_table)

#Flatten array

new_flarr = mix.flatten()

print("\nOriginal array:\n", mix)
print("Fattened array:\n", new_flarr)

# An example array

#slicing array
temp = mix[:2,::4]
print("Array with first 3 rows and alternate"
     "coloumns(0,3):\n", temp)

temp = mix[:1,::2]
print("Array with first 3 rows and alternate"
     "coloumns(0,3):\n", temp)

#Integer array indexing example
temp = mix[1][1][1]
print("\nElements at indices (0,0), (1,1),(2,2),"
     "(3,3):\n", temp)

#boolean array indexing examples
cond = mix > 0 #cond is a boolean array
temp = mix[cond]
print("\nElements greater than 0:\n", temp)

Array is of type: <class 'numpy.ndarray'>
No. of dimension: 3
Shape of array: (2, 2, 5)
Size of array: 20
Array stores elements of type: float64
Array created using passed list:
 [[[ 10.   20.  -30.   40.   50. ]
  [  6.   -8.   74.   96.   12.3]]

 [[ 15.    8.    9.6  -9.   12. ]
  [  5.    1.  -15.   20.   25. ]]]

Array created using passed typle:
 [ 10  20  30  40  50  60  70  80  90 100]

An array initialized with all zeros:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

An array initialized with all 8s.Array type is complex:
 [[8.+0.j 8.+0.j 8.+0.j 8.+0.j 8.+0.j 8.+0.j 8.+0.j]
 [8.+0.j 8.+0.j 8.+0.j 8.+0.j 8.+0.j 8.+0.j 8.+0.j]
 [8.+0.j 8.+0.j 8.+0.j 8.+0.j 8.+0.j 8.+0.j 8.+0.j]]

A Random array
: [[0.42445156 0.7030477  0.26672637]
 [0.57242984 0.92283423 0.16934113]
 [0.61732218 0.11995052 0.36609805]]

A Sequential array with steps of 5
: [ 1  6 11 16 21 26 31 36 41 46]

A Sequential array with 10 values between0 to 5
: [ 1.   13.25 25.5  37.75 50.  ]

O

In [63]:
#Statement to import the numpy library
import numpy as np

# Array Inspection

A numpy array has following attributes 

1. ndarray.shape

2. ndarray.ndim

3. ndarray.size

4. ndarray.dtype

5. ndarray.astype


# 1. ndarray.shape

This return a typle consisting of array dimensions and can be used to resize the array

In [64]:
alma_array = np.array([[1,2,3],[4,5,6]])
print(alma_array.shape)

(2, 3)


In [65]:
alma_array = np.array([[1,2,3,4],[4,5,9,10]])
print(alma_array.shape)

(2, 4)


In [66]:
alma_array = np.array([[[1,2,3],[4,5,6]],
                      [[1,2,3],[4,5,6]],
                      [[1,2,3],[4,5,6]],
                      [[1,2,3],[4,5,6]]])
#print(alma_array)
print(alma_array.shape)

(4, 2, 3)


In [67]:
#statement to import the numpy library
import numpy as np

In [68]:
alma_array = np.array([[[1,2,3],[4,5,6]],
                      [[1,2,3],[4,5,6]],
                      [[1,2,3],[4,5,6]],
                      [[1,2,3],[4,5,6]]])
print(alma_array)
print(alma_array.shape)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(4, 2, 3)


In [69]:
alma_array

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

# 2. ndarray.ndim

**This returns the number of array dimensions**

In [70]:
array_of_integers = np.array([0,1,2,3,4,5,6,7,8,9])
print("Dimensions of 'array_of_integers'=",array_of_integers.ndim)

simple_2D_array = np.array([[1,2,3],[4,5,6]])
print("Dimensions of 'simple_2D_array'=",simple_2D_array.ndim)

Dimensions of 'array_of_integers'= 1
Dimensions of 'simple_2D_array'= 2


**This returns the total number of elements in the array**

In [72]:
#print the size of array
array_of_integers = np.array([0,1,2,3,4,5,6,7,8,9])
print(f"The total number of elemets in our array'array_of_integers'= {array_of_integers}")

simple_2D_array = np.array([[1,2,3],[4,5,6]])
print(f"The total number of elemets in our array'simple_2D_array'= {simple_2D_array}")

The total number of elemets in our array'array_of_integers'= [0 1 2 3 4 5 6 7 8 9]
The total number of elemets in our array'simple_2D_array'= [[1 2 3]
 [4 5 6]]


# 3. size

In [74]:
import numpy as np
#creating array object
arr = np.array([[1,2,3],
               [4,2,5]])
#printing size (total number of elements) of array
print("size of array:", arr.size)

size of array: 6


# 4. ndarray.dtype

**This returns the data type of the array**

In [75]:
#statement to import the numpy library
import numpy as np


In [76]:
#print the dtype of array
my_array = np.array([1,2,3,4,5])
print(my_array.dtype)


int32


In [77]:
#print the dtype of another array
my_array = np.array([1,2,0,3,4,5])
print(my_array.dtype)


int32


# 5. ndarray.astype

**This changes the data type of an array**

In [78]:
#Create an array
arravali = np.array([2,3,4])
print(arravali)
print(arravali.dtype)

# change the data type of the array to float
arravali_ = arravali.astype('float64')
print(arravali_)
print(arravali_.dtype)

#change the datatype of the array to string
arravali_as = arravali.astype('string_')
print(arravali_as)
print(arravali_as.dtype)

[2 3 4]
int32
[2. 3. 4.]
float64
[b'2' b'3' b'4']
|S11


# Why numpy?

Numpy data structures perform better in:

**Memory** = Numpy data structures take up less space.

**Performance** = they have need for speed and are faster than lists.

**Functionality** = Scipy and numpy have optimized functions such as linear algebra operations built in.

# Memory

In [82]:
#import library
import numpy as np
#create a numpy 1d-array
x = np.array([100,20,34,7,79,67])
print("Size if the array:", x.size)
print("Memory size of one element in bytes:",x.itemsize)
#memory size of numpy array in bytes
print("Memory size of numpy array in bytes:", x.size* x.itemsize)

Size if the array: 6
Memory size of one element in bytes: 4
Memory size of numpy array in bytes: 24


In [83]:
#import library
import numpy as np

#create a numpy 2d-array
x = np.array([[100,20,34],
             [300,400,600]])
print("size of the array :", x.size)
print("Memory size of one element in bytes:",x.itemsize)
#memory size of numpy array in bytes
print("Memory size of numpy array in bytes:", x.size* x.itemsize)

size of the array : 6
Memory size of one element in bytes: 4
Memory size of numpy array in bytes: 24


In [84]:
import sys
#declaring a list of 10 elements
s = [0,1,2,3,4,5,6,7,8,9]
print("Size of each element of list in bytes:",sys.getsizeof(s))
print("Size of whole list is bytes:", sys.getsizeof(s)* len(s))   # 136*10

#declaring a Numpy array of 10 elements
D = np.array([0,1,2,3,4,5,6,7,8,9])
print("Size of each element of list in bytes:",D.itemsize)
print("Size of whole list is bytes:", D.itemsize* D.size)   

Size of each element of list in bytes: 136
Size of whole list is bytes: 1360
Size of each element of list in bytes: 4
Size of whole list is bytes: 40


# Performance

In [86]:
import numpy as np
import time

#size of array and lists.
size = 100000

#declaring lists
list1 = range(size)
list2 = range(size)

#declaring arrays
array1 = np.arange(size)
array2 = np.arange(size)

#capturing time before the mulitiplication of python lists
initailTime =time.time()

#multiplying elements of both the lists and stored in another list
resultantlist = [(a*b) for a, b  in zip(list1,list2)]

#calculating execution time 
print("Time taken by lists to perform multiplication:",
     (time.time() - initailTime), "seconds")

#capturing time before the multiplication of numpy arrays
initailTime = time.time()

#multiplying elements of both the numpy arrays and stored in another numpy are 
resultantArray = array1 *array2

#calculating execution time
print("Time taken by arrays to perform multiplication:", 
     (time.time() - initailTime), "second")

Time taken by lists to perform multiplication: 0.011216878890991211 seconds
Time taken by arrays to perform multiplication: 0.0 second


# Functionality 

In [88]:
import numpy as np
#declaring a list 
ls = [1,2,3]

#converting the list into a numpy array
arr = np.array(ls)

try:
    #adding 4 to each elements of list
    ls = ls+4
    
except(TypeError):
    print("Lists don't support list+ int")
    
#now on array

try :
    #adding 4 to each numpy array
    arr =arr+4
    
    #print the numpy array
    print("Modified numpy array:", arr)
    
except(TypeError):
    print("Numpy array don't support list+ int")

Lists don't support list+ int
Modified numpy array: [5 6 7]


# Different ways of creating an adarray

# Uninitialized 

In [89]:
#Statement to import the numpy library 
import numpy as np

In [90]:
#creating an uninitialized array of a specified shape 
uninitailized_array = np.empty([5,3], dtype=int)
print(uninitailized_array)

[[121 195 817]
 [151 471 159]
 [874 963 524]
 [846 487 856]
 [987 415 265]]


In [91]:
#Intializing the array with zeros
zeros_array = np.zeros((3,3))    #Default dtype = float
another_zeros_array = np.zeros((4,3), dtype=int)
print(zeros_array)
print(another_zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [92]:
#Intializing the array with zeros
zeros_array = np.zeros((4,4))    #Default dtype = float
another_zeros_array = np.zeros((4,4), dtype=int)
print(zeros_array)
print(another_zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


# Initailized with ones

In [93]:
#Intializing the array with ones
ones_array = np.ones((3,3))    #Default dtype = float
another_ones_array = np.ones((4,3), dtype=int)
print(ones_array)
print(another_ones_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [94]:
bunch_of_ones = np.ones((4,3))
bunch_of_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [95]:
#Trying to change the shape of our array
bunch_of_ones.shape = (2,6)
bunch_of_ones

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

# Array from numerical ranges

In [96]:
#Array with values from 0 to N
array_with_range = np.arange(5)
array_with_range

array([0, 1, 2, 3, 4])

In [97]:
#set start and stop parameters
#parameters for the function - np.arange(start, stop, step,dtype)
#Default dtype is that o fthe input given
another_array_with_range = np.arange(10,20,2)
another_array_with_range

array([10, 12, 14, 16, 18])