# Pandas

Pandas is a python package providing fast, flexible and expressive data structures designed to make working with structured 
(tabular, multidimensional, potentially heterogenous) and time series data both easy and intuitive. it aims to be the fundamental high-level
building block for doing practical, real world data analysis in python.

Pandas is designed to make it easier to work with structured data. most of the analysis you might perform will likely involve using tabular data,
e.g., from .cvc files or relational databases(e.g., SQL). The dataframe object in pandas is "Two-dimensional tabular, column- oriented data structure
with both row and columns labels."

Here are just a few of the things that pandas does well:

Robust IO Tools for loading data from flat files (CVC and delimited), Excel files, data bases, and saving/loading data from the ultrafast 
HDF5 format Easy handaling of missing data (represented as NaN) in floating point as well as non-floating point data.

**Size mutability:** columns can be inserted and deleted from data frame and higher dimentional objects automatic and explicit.
    
**Data alignment:** Object can be explicitly  aligned to a set of labels o the user can simply ignore the labels and leyt series,
    dataframe etc. automatically align the data for you in computation powerful, flexible group by functionlity to perform split-apply-combine
    operations on data sets, for aggregating and transforming data make it easy to convert ragged, differently- indexed data in other python and numpy data 
    structures into dataframe objects intelligent label-based slicing, fancy indexing and subsetting of large data set intuitive  merging and 
    joining data sets flexible re-shaping and pivoting of data sets Hierarchical labeling of axes (possible to have multiple lables per tick)
    
**Tine series- specific functionality:** Data  range generation and frequency conversion, moving window statistics, moving window linear regression,
    data shifting and lagging.

# If you're curious:

Thw pandas name itself is derived from panel data, an econometrics term for multidemensional structured data sets, and python data 
analysis itself. After getting introduced, you consult the full pandas documentation.

In [12]:
#Import package 
import pandas as pd
import numpy as np

In [13]:
#Version of pandas
pd.__version__

'1.5.3'

# What are pandas Dataframes?

In the chapters introducing python lists and numpy arrays, ypu learn the both of these data structures can store collections of values, instead of just single
values. You also learned that while python lists are flexible and can store data items of various types (e.g. intergers, floats, text strings), numpy arrays require all data elements to be of the same type.
Because of this requirement, numpy arrays can provide more functionality for running calculating such as element-by-element arithmetic operations (e.g. multiplication of each element in the numpy array 
by the same value) that python lists do not support . You may now be noticing that each data structure provides different functionality that can be useful in different workflows. .
In this chapter, you will learn about pandas dataframes, a data structure in python that provides the ability to work with tabular data.
pandas dataframes are composed of rows and columns that can have header names. and the columns in pandas dataframes can be different types 
(e.g. the first columns containing integers and the second columns containing text strings). Each value in pandas data frame is 
referred to as a cell that has a specific row and column index within  the tabular structure.

# There are two central concepts which you should know about:

**Series :** A series is essentially a column
    
**Data frame:** A dataframe is a two-dimensional data structure, i.e., data is aligned in a tabular fashion in rows and columns.
    Pandas dataframe consists of three principal components, the data, rows, and columns.

# Distingushing characteristic of Pandas Dataframe

These characteristics(i.e tabular format with rows and columns that can have headers) make pandas dataframes very versatile for not only storing different
types, but for maintaining the relationship between cells across the same row and/ or column.

Recall that in the chapter on numpy arrays, you could not easily connect the values across two numpy arrays. such as thosefor precip and months.
Using a pandas dataframe, the relationship between the value january in the month column and the value 0.70 in the precip column in mantained.

These two values (Apples and 3) are considered part of the same record, representing the same observation in the pandas data frame. In addition, pandas 
dataframe have other unique characteristics that differentiate them from other data structures:
    
Each column in a pandas dataframe can have a  lable name (i.e. header name such as Oranges) and can contain a different type of data 
from its neighboring columns. By default, each row  has an index within a range of values beginning at [0]. However, the row index in pandas dataframes 
can also be set as labels(e.g. a location name data). All cells in a pandas data frame have  both a row index and a column index (i.e. two-dimensional table structure).
even if there is only ome cell(i.e. value) in the python dataframe. In addition to selecting cells through location-based indexing 
(e.g. cell at row1, column1),  you can also query for data within pandas dataframes based on specific values (e.g. querying for text strings or 
numeric values). Because of the tabular structure, you can work with cells in pandas dataframes.

across an entire row 

across an entire column (or series, a one- dimentional array in pandas)

by selecting cells based on location or spectific values.

# Let us go ahead and create our first pandas series

In [2]:
import pandas as pd
#our first series

number_series = pd.Series([2,3,5,6,8])
print(number_series)

0    2
1    3
2    5
3    6
4    8
dtype: int64


In [5]:
# same series but with different indices
number_series = pd.Series([2,3,5,6,8], index = ['a','b','c','d','e'], name = 'Number')
print(number_series)

a    2
b    3
c    5
d    6
e    8
Name: Number, dtype: int64


In [6]:
print(number_series[0])
print(number_series['a'])

2
2


# Let us go ahead and create our first pandas

**Data frame**

# Using a 2-D NumPy array

In [7]:
import numpy as np
import pandas as pd
some_2D_array = np.random.randint(2,35,(3,10))
print(some_2D_array)

[[ 2 18  8  9 11 20 25 26 13  5]
 [ 9  2 29  9 34 16  8 30  8 18]
 [32 20 27 10 11  7  7 22  9 15]]


In [8]:
#creating our first dataframe
some_2D_array = np.random.randint(2,6,(3,4))
first_dataframe = pd.DataFrame(some_2D_array, columns= ['Aniket', 'Akshay', 'Eknath', 'Ashwini'])
first_dataframe

Aniket  Akshay  Eknath  Ashwini
0       3       2       5        4
1       5       3       5        4
2       5       2       3        3

# Using a conventional list of lists

In [4]:
#Initialize list of lists
import pandas as pd
list_of_lists = [['Amar',10, 'Pune'], ['Akbar',15,'mumbai'],['Anthony',14, 'Delhi']]
#create the pandas dataframe
df = pd.DataFrame(list_of_lists, columns = ['Name', 'Age', 'city'], index = ['a','b','c'])
#print dataframe
df

Name  Age    city
a     Amar   10    Pune
b    Akbar   15  mumbai
c  Anthony   14   Delhi

# Using a dictionary

In [5]:
#STore the data in a dictionary
employee_dict = {'Employee Name':['Rajeev', 'Sumit','Aviral'], 'Income':[200000,100000,90000],'Package':[9,10,11]}

#Create Dataframe
employee_df = pd.DataFrame(employee_dict)
#print the dataframe
employee_df

Employee Name  Income  Package
0        Rajeev  200000        9
1         Sumit  100000       10
2        Aviral   90000       11

In [6]:
#Store the date in a dictionary
series_dict = {'First Series': pd.Series([10,20,30,40]), 'Second Series':pd.Series([100,200,300,400])}
#Create the Dataframe using the dictionary
df = pd.DataFrame(series_dict)
#print the dataframe
df

First Series  Second Series
0            10            100
1            20            200
2            30            300
3            40            400

# Using a list of dictionaries

In [7]:
import pandas as pd

In [8]:
#Initialise the list of dictionaries
list_of_dicts = [ {'a':1,'b':2,'c':3},{'a':10, 'b':20,'c':30},{'a':'Ganesh','b':'Supriya'}]
df = pd.DataFrame(list_of_dicts)
df

a        b     c
0       1        2   3.0
1      10       20  30.0
2  Ganesh  Supriya   NaN

In [9]:
#What happens if the number of keys are different in the Two dictioneries 
list_of_dicts = [{'a':2,'b':3}, {'a':10, 'b':20, 'c':30}, ]
df = pd.DataFrame(list_of_dicts, index = ['First', 'Second'])
df

a   b     c
First    2   3   NaN
Second  10  20  30.0

# There are other ways too

In [10]:
import numpy as np
#list of names
actor_names = ['Ryan Reynolds', 'Benedict Cumberbatch', 'Robert Downey Jr.', 'Chris Evans']
#List of their ages
actor_age = [48,62,54,np.nan]
#Get the lsit of tuples by zipping the two lists together
list_of_tuples = list(zip(actor_names, actor_age))
print(list_of_tuples)
#Converting the listof tuples into pandas Dataframe
actor_df = pd.DataFrame(list_of_tuples, columns = ['Name','Age'])
#print the dataframe
actor_df

[('Ryan Reynolds', 48), ('Benedict Cumberbatch', 62), ('Robert Downey Jr.', 54), ('Chris Evans', nan)]


Name   Age
0         Ryan Reynolds  48.0
1  Benedict Cumberbatch  62.0
2     Robert Downey Jr.  54.0
3           Chris Evans   NaN

**So we have seen a variety of ways in which we can create simple dataframes. Now let us explore few methods and associated with the pandas dataframes in python**

# We can print the indices of our dataframe using the index attribute

In [11]:
list(actor_df.index)

[0, 1, 2, 3]

# Let us create a dataframe with 100 rows and 5 columns

In [12]:
import numpy as np

In [13]:
#Create an array of shape(20,7)
our_array = np.random.randn(20,7)
df = pd.DataFrame(our_array, columns = ['A','B','C','D','E','F','G'])
df

A         B         C         D         E         F         G
0   1.312613  0.256295  0.679862  0.369337  0.810532 -0.992385 -0.557960
1  -0.748546  0.181505 -1.482877 -1.164180  1.397296 -0.793839 -1.399992
2  -0.907437 -0.288978 -0.231920  0.052950 -1.190213  0.113190  1.256856
3  -0.642497 -0.775272  0.351090  0.351538  0.323957 -1.811922  0.672874
4  -0.599299  1.772703 -1.766785 -0.442878  1.121333  0.225415  0.122346
5  -1.605533  0.267894  0.624044  0.671828 -0.580772  0.329491 -0.428911
6   0.326315  0.849488  0.116211  1.473569  0.021822 -0.254924  0.236418
7   0.332224  0.498889 -0.486641 -1.825576  0.705958  0.082606  1.647303
8   1.405373 -1.230798  0.574237  1.188308 -0.201690  0.393854  0.232206
9  -0.588025 -0.360470 -0.205031 -0.472429 -0.408599 -1.419269 -0.755120
10  1.425973  0.747717  0.860560 -1.646824  2.065448  0.516605 -0.702591
11 -0.106732  0.620934  0.192952 -0.585881  0.352738  0.497645  0.628057
12  0.567326  0.118687 -0.382285  0.983909  0.265141  1.469460  1.221340
13 -0.162303 -1.324181 -0.657143  0.566680  1.294652  0.810198  0.697288
14  1.823496 -0.052316 -0.074647 -0.068028 -0.268900 -1.374613 -0.107463
15 -0.019184  0.626065  0.754302  1.097239  1.384631  1.129968 -1.564641
16  0.858501  0.166828 -0.704568  0.532731  0.331164  1.299236 -0.890783
17  0.146092 -0.810906  0.076413 -1.357905  1.179224 -0.613416  1.627701
18  0.792602  1.988414  0.270013  0.251558  0.682612 -0.123467  0.786318
19  0.988810 -1.395923 -1.018949 -0.480577  0.638101  0.726811  0.489536

In [28]:
list_of_dicts = [{'Name':'Aniket','Age':26, 'Gender':'Male'}, {'Name':'Prasad','Age':27, 'Gender':'Male'}, 
                 {'Name':'Anjali','Age':25, 'Gender':'Female'},{'Name':'Shraddha','Age':24, 'Gender':'Female'}]
actor_df = pd.DataFrame(list_of_dicts, index = ['1','2','3','4'])
actor_df

Name  Age  Gender
1    Aniket   26    Male
2    Prasad   27    Male
3    Anjali   25  Female
4  Shraddha   24  Female

In [26]:
series_dict = {'Name': pd.Series(['Aniket','Eknath','Keshav','Nehal']), 'Rank':pd.Series([1,2,3,4])}
#Create the Dataframe using the dictionary
df = pd.DataFrame(series_dict)
#print the dataframe
df

Name  Rank
0  Aniket     1
1  Eknath     2
2  Keshav     3
3   Nehal     4

In [34]:
series_dict = {"Name":['Aniket', 'Ajay', 'Amit', 'Mohit'], "Age":[26,25,26,25]}
df = pd.DataFrame(series_dict)
df

Name  Age
0  Aniket   26
1    Ajay   25
2    Amit   26
3   Mohit   25

In [38]:
df.describe()

Age
count   4.00000
mean   25.50000
std     0.57735
min    25.00000
25%    25.00000
50%    25.50000
75%    26.00000
max    26.00000