In [2]:
#input 
a = int(input("Enter first number : "))
b = int(input("Enter second number : "))
print(a+b)

Enter first number : 10
Enter second number : 10
20


In [3]:
a = input()
print(a)

Aniket
Aniket


In [3]:
a = input("City = ")
print("City name " + a + " Main")


SyntaxError: unterminated string literal (detected at line 2) (503076305.py, line 2)

In [3]:
#If elif and else statements.
a = int(input("Temperature in degree : "))
print("your city temperature is :", a)
if (a>18):
    print("High")
elif (a>12):
    print("Normal")
else:
    print("Low")

Temperature in degree : 45
your city temperature is : 45
High


In [4]:
print("Aniket")

Aniket


In [5]:
name = "Aniket"
for i in name:
    print(i)

A
n
i
k
e
t


In [6]:
name = "Aniket"
for i in name:
    print(i,end=",")

A,n,i,k,e,t,

In [7]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [23]:
for i in range(10,0):
    print(i)
    i = i - 1

In [22]:
for i in range(0,100,20):
    print(i)

0
20
40
60
80


In [15]:
i = 1
while (i<=10):
    print(i)
    i = i+1

1
2
3
4
5
6
7
8
9
10


In [16]:
i = 10
while (i>0):
    print(i)
    i=i-1

10
9
8
7
6
5
4
3
2
1


In [20]:
print("Aniket")

Aniket


In [1]:
Name = "Aniket"
print(Name)

Aniket


In [2]:
type(Name)

str

In [3]:
Aniket = [1,15,6,9,7,5]
Mohit = (15,85,96,15)
Nehal = {15,18,98,75}
Friend = (Aniket,Mohit,Nehal)
print(Friend)

([1, 15, 6, 9, 7, 5], (15, 85, 96, 15), {18, 75, 98, 15})


In [4]:
Friend = (*Aniket,*Mohit,*Nehal)

In [5]:
print(Friend)

(1, 15, 6, 9, 7, 5, 15, 85, 96, 15, 18, 75, 98, 15)


In [12]:
for i in range(1,51):
    if i % 2  == 0:
        print(i+1, end= ','
     else:
        print(i-1, end=',')


0,3,2,5,4,7,6,9,8,11,10,13,12,15,14,17,16,19,18,21,20,23,22,25,24,27,26,29,28,31,30,33,32,35,34,37,36,39,38,41,40,43,42,45,44,47,46,49,48,51,

In [14]:
for i in range(1,11):
    if i % 2  == 0:
        print((i*i*i)-1 , end= ',')
    else:
        print((i*i)+1, end=',')

2,7,10,63,26,215,50,511,82,999,

In [17]:
for i in range(1,11):
    if i % 2  == 0:
        print((i*3)+1 , end= ',')
    else:
        print((i*3)-1, end=',')

2,7,8,13,14,19,20,25,26,31,

In [62]:
previous_value = 0
for i in range(1,11):
    sum =(i+previous_value)
    previous_value = sum
    print(sum)
        

1
3
6
10
15
21
28
36
45
55


In [66]:
n = input('Enter Number:')
a = int(n)
sum_1 =0
for i in range(1,a+1):
    sum_1 = sum_1*10+1
    print(sum_1)
    

Enter Number:10
1
11
111
1111
11111
111111
1111111
11111111
111111111
1111111111


In [69]:
#Take a number from user & print all odd natural numbers till N.
n = int(input('Enter Number:'))
for i in range (1,n+1):
    if i % 2  == 1:
        print(i, end= ',')


Enter Number:20
1,3,5,7,9,11,13,15,17,19,

In [1]:
#Take 3 integer from user & find the greatest.
a = int(input("Enter 1st value:"))
b = int(input("Enter 2nd value:"))
c = int(input("Enter 3rd value:"))
if  (a>b)&(a>c):
    print("A is greater then B and C")
elif (b>a)&(b>c):
    print("B is greater then A and C")
else:
    print("C is greater then A and B")

Enter 1st value:10
Enter 2nd value:20
Enter 3rd value:30
C is greater then A and B


In [3]:
#take any integers from user and check if it's unit, tens or hundered.
n = int(input('Enter Number:'))
if (n <= 9)&(n >= -9):
    print("This is unit")
elif (n <=99)&(n >= -99):
    print("This is tens")
else :
    print("This is hundred")

Enter Number:-183
This is hundred


In [1]:
n = int(input('Enter Number:'))
sum = 0 
sum_1 = 0
for i in range(1,n+1):
    if i % 2  == 1:
        sum+=i
    else :
        sum_1+=i
print('Addition of all odd number is:', sum )
print('Addition of all even number is:', sum_1)

Enter Number:10
Addition of all odd number is: 25
Addition of all even number is: 30


In [8]:
n = int(input('Enter Number:')) 
Factorial = 1
for i in range(1,n+1):
    Factorial=Factorial*i
print(Factorial)

Enter Number:7
5040


In [36]:
from array import*
new_array = array('i',[])
n = int(input("Number of elements:"))
pCount = 0
nCount = 0
zCount = 0
for i in range(n):
    new_array.append(int(input("Enter element:")))
for i in range(len(new_array)):
    print(new_array[i])
    if (new_array[i] > 0):
        pCount +=1
    elif (new_array[i] < 0):
        nCount +=1
    else:
        zCount +=1
print("positive numbers :",pCount)
print("negative numbers:",nCount)
print("zero:",zCount)


Number of elements:5
Enter element:9
Enter element:8
Enter element:0
Enter element:-9
Enter element:-8
9
8
0
-9
-8
positive numbers : 2
negative numbers: 2
zero: 1


In [37]:
from array import*
new_array = array('i',[])
n = int(input("Number of elements:"))
pCount = 0
for i in range(n):
    new_array.append(int(input("Enter element:")))
for i in range(len(new_array)):
    print(new_array[i])
    if (new_array[i] %7 == 0):
        pCount +=1
print("numbers divisible by 7 are :",pCount)


Number of elements:10
Enter element:7
Enter element:65
Enter element:49
Enter element:3
Enter element:21
Enter element:97
Enter element:63
Enter element:8
Enter element:6
Enter element:9
7
65
49
3
21
97
63
8
6
9
numbers divisible by 7 are : 4


In [2]:
x = int(input("Enter a number: "))
reverse = 0 
while (x >0):
    remainder = x % 10
    reverse = (reverse*10) + remainder
    x = x // 10
print(reverse)

Enter a number: -1234
0


In [46]:
print('23')

23


In [1]:
x = int(input("Enter a number: "))
plus = 0 
while (x >0):
    plus = plus + x % 10
    x = x//10
print(plus)

Enter a number: 259
16


In [6]:
x = int(input("Enter a number: "))
odd_numbers = 0 
number = 0
while (x >0):
    odd_numbers = x % 10
    x = x//10
    if (odd_numbers % 2  == 1):
        number = number +odd_numbers
print(number)

Enter a number: 4898746
16


In [1]:
print("aniket")

aniket


In [10]:
x = int(input("Enter a number: "))
reverse = 0 
palin = x
while (x >0):
    remainder = x % 10
    reverse = (reverse*10) + remainder
    x = x // 10
if (palin==reverse):
    print("it's a palindrome")
else :
    print("it's not a palindrome")

Enter a number: 156849
it's not a palindrome


In [1]:
import numpy as np

In [16]:
myarr = np.array([[3,6,85,9]], np.int64)

In [17]:
print(myarr)

[[ 3  6 85  9]]


In [18]:
myarr.shape

(1, 4)

In [19]:
myarr[0,3]

9

In [26]:
myarr[0,1]

6

In [27]:
myarr.dtype

dtype('int64')

In [28]:
myarr

array([[ 3,  6, 85,  9]], dtype=int64)

In [29]:
myarr[0,3] = 45

In [30]:
myarr

array([[ 3,  6, 85, 45]], dtype=int64)

In [8]:
# Write a program were we need to take a input from user and print the remainder for divisible by 2
# Input: 34
# Output: 0

x = int(input("Enter a number: "))
print(x/2)
    

Enter a number: 21
10.5
